### ISSUE TITLE
Accent color does not update in shade row

### ISSUE THREAD

**Issue by peterkos** [fluid-design-io/color-ui-generator#2] opened 2024-06-19 19:05 UTC
Hello!

This is a very pretty site :) 

I noticed that changing the accent color does not update its row on the right. 
1. Pick colors
2. Change accent color
3. Expected: shade row on right updates to reflect new base accent color
4. Actual: shade row does not animate or change colors

I was able to kick it into action by fiddling the colorblind sliders a bit. Didn't see any info in the console log that might help, but hopefully that's a start?

| Before | After |
|---|---|
|![CleanShot 2024-06-19 at 15 02 17@2x](https://github.com/fluid-design-io/fluid-design/assets/2782749/4ab20668-cea1-4b09-ba2c-155182745591)|![CleanShot 2024-06-19 at 15 03 31@2x](https://github.com/fluid-design-io/fluid-design/assets/2782749/220c9808-c3fc-4c06-aca5-f0419f44a7af)|

**Comment by peterkos** [comment] 2024-06-19 19:06
Also (and this is my "not a designer" excuse 😅) -- is there a reason why the base colors don't show up on the rows on the right? e.g., the original `#463164` is not exactly shown in the primary color row on the top right.

**Comment by fluid-design-io** [comment] 2024-06-19 20:18
Hey @peterkos, thanks for your kind words! I can confirm this behavior. Most likely, it is due to states not being "triggered" when the color picker changes. I was pretty aggressive about optimizing the performance and may have "overdone" it.

I've been thinking about ways to improve the base code structure and implement [`Next.js` PPR](https://nextjs.org/learn/dashboard-app/partial-prerendering) alone with [React Complier](https://react.dev/learn/react-compiler) to do the heavy lifting optimizing the performance, it's been some time since the last update...

Looking into this issue...

**Comment by fluid-design-io** [comment] 2024-06-19 20:23
> Also (and this is my "not a designer" excuse 😅) -- is there a reason why the base colors don't show up on the rows on the right? e.g., the original `#463164` is not exactly shown in the primary color row on the top right.

I notice I've never include this page anywhere explaining the "how", here it is: https://colors.fluid-design.io/how
It talked about my philosophy of making the colors being cohesive and feel "right" in all color steps, so the chosen color might not show up on the palette. Hope it makes sense?

**Comment by fluid-design-io** [comment] 2024-06-24 06:31
Hey @peterkos! This issue should be fixed :)

**Closed as completed by fluid-design-io** 2024-06-24 06:31 UTC
Labels: bug

**Comment by peterkos** [comment] 2024-06-24 18:19
Thanks so much! :D
